name = "AFMsimulations"
uuid = "5cfa06bf-2d9d-4196-b117-af8e322e50b7"
authors = ["Hannes Wallner"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
DifferentialEquations = "7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
